### ISSUE TITLE
Pydantic model?

### ISSUE THREAD

**Issue by vdavez** [dherincx92/fpds#17]
Hi @dherincx92—I have been wondering whether it might be worth creating [Pydantic models](https://docs.pydantic.dev/latest/) for FPDS data. The use case I'm envisioning is to allow for easier export from FPDS into a database that matches the USASpending database. 

See the USASpending model here: https://github.com/fedspendingtransparency/usaspending-api/blob/master/usaspending_api/transactions/models/source_procurement_transaction.py

I'm not *sure* if it's worth it or not, but thought I'd float it and see if you had any reactions. I'd be happy to take a swing at doing some of the modeling / creating a PR if you think it's useful. Thanks!

**Comment by dherincx92** [comment]
I do like this idea, but one potential pitfall I see is that this would require consistent maintenance of the model itself; at work I've encountered a similar issue and we've overcome this by either:

A) Ingesting each record in its raw JSON format and then modifying SQL models downstream with dbt or any regular ol' SQL script
B) Using a data catalog tool like AWS Glue to handle automatic schema detection and alter/create new columns based on data ingestion.
