### ISSUE TITLE
Consider a generator?

### ISSUE THREAD

**Issue by vdavez** [dherincx92/fpds#18]
This might be me thinking about this all wrong, so bear with me. But one thing I am currently doing is taking the FPDS requests, taking the JSON, and loading them into a DB. For large FPDS requests, this is quite memory intensive. Right now, I've written a script that intercepts at the `multiprocess_jsonified_entries` step. But that still means all of the FPDS requests happen in the asyncio loop before and the memory builds up while processing it.

All of which is a long way of saying: I wonder if there's a way to be _even_ lazier around the FPDS request and/or expose the JSON files in more of a streaming way so that I don't overheat my computer in the meantime lol. 

Or, I could be doing it wrong. 😂

**Comment by dherincx92** [comment]
@vdavez sorry for the delay...had some life stuff come up. Will do...just had to deal with a similar issue elsewhere so can definitely take a stab at this.

**Comment by dherincx92** [comment]
Will address this one in a subsequent PR. This one should be pretty straightforward. I'll make this a minor release.

**Comment by dherincx92** [comment]
Closing the loop here. Now if you run and get results, you will get a generator. See `README.md` on version `1.4.0`

**Comment by vdavez** [comment]
This is amazing! Thank you @dherincx92!
