### ISSUE TITLE
Dependency updates

### ISSUE THREAD

**Issue by vdavez** [dherincx92/fpds#4]
👋 I love this package! Thank you for creating it! Would you be open to me sending a pull request that updates some of the dependencies? I am having a dependency conflict with requests `2.28.1` and `^2.28.2`. I tested locally with removing the pinned dependencies in requirements.txt and setup.cfg and everything seems to work. Thanks again!

**Comment by dherincx92** [comment]
Hey @vdavez ! All pull requests are welcome!

**Comment by vdavez** [comment]
Amazing! Thank you. Just submitted one.
