### ISSUE TITLE
awardContractID versus referencedIDVID

### ISSUE THREAD

**Issue by vdavez** [dherincx92/fpds#6]
If I correctly understand how this works, right now the parser does not differentiate between the award and the referenced IDV, so that it presents only `agencyID`, `PIID`, `modNumber` without presenting them as `awardContractID__agencyID` `awardContractID__PIID`, and `awardContractID__modNumber`, etc...

It would be amazing if you could distinguish between them. I'll try and figure out what it would take to do this, but if you know off the top of your head and/or have a suggestion about where to look, I'd be happy to submit another PR.

Thanks!

```xml
<ns1:awardID>
    <ns1:awardContractID>
        <ns1:agencyID name="ENVIRONMENTAL PROTECTION AGENCY">6800</ns1:agencyID>
        <ns1:PIID>0002</ns1:PIID>
        <ns1:modNumber>P00018</ns1:modNumber>
        <ns1:transactionNumber>0</ns1:transactionNumber>
    </ns1:awardContractID>
    <ns1:referencedIDVID>
        <ns1:agencyID name="ENVIRONMENTAL PROTECTION AGENCY">6800</ns1:agencyID>
        <ns1:PIID>EPS31703</ns1:PIID>
        <ns1:modNumber>0</ns1:modNumber>
    </ns1:referencedIDVID>
</ns1:awardID>
```

**Comment by dherincx92** [comment]
So would it be beneficial if there was a column that just delineated between `AWARD` and `IDV`? Let me check my code. It shouldn't be too hard. The hierarchy of this XML is quite annoying in some ways. It might be an issue on my end. Let me take a stab at it.

**Comment by vdavez** [comment]
That would be excellent. Yeah, if you have (for example) a task order against an IDIQ, it's useful to know the PIID of the task order and the PIID of the IDIQ.

**Comment by vdavez** [comment]
I squinted hard enough at the code to figure out what's happening.... Because the elements (awardContractID and referencedIDVID) have children, this part of the code is kicking it out: https://github.com/dherincx92/fpds/blob/e145dd75df2da4f0c341d520f771353686370120/src/fpds/core/parser.py#L329-L331

I haven't thought much about how to _fix_ that, but that's definitely what's happening...

**Comment by dherincx92** [comment]
Yup, I'm working on an updated release. Give me a few days to properly display the hierarchy of elements. That was the toughest part of the code.

**Comment by dherincx92** [comment]
@vdavez I have a preliminary working version that looks to give you the entire nested structure of the tags. Some of the tags are quite long, but I'll leave the data cleaning and parsing up to the end user. Let me write some tests and validate the work. I should have something by the end of this weekend or early next week.

**Comment by dherincx92** [comment]
@vdavez PR #8 is functional. I still need to add tests and tidy up the function types. But here is a snippet of how the data is now represented. Some of the tags have empty whitespace since they technically don't contain data. Despite this, I want to leave it to users to perform data cleaning...this is in anticipation of possible future changes to the data. I want to run some more rigorous tests, but wanted to let you know that if you wanted something to get going, this PR branch should suffice. I did some extensive rehaul.

```
    "contractID": "\n          ",
    "contractID__IDVID": "\n            ",
    "contractID__IDVID__agencyID": "4740",
    "contractID__IDVID__agencyID__name": "PUBLIC BUILDINGS SERVICE",
    "contractID__IDVID__PIID": "47PA0320A0001",
    "contractID__IDVID__modNumber": "PA0009",
    "contractID__referencedIDVID": "\n            ",
    "contractID__referencedIDVID__agencyID": "4732",
    "contractID__referencedIDVID__agencyID__name": "FEDERAL ACQUISITION SERVICE",
    "contractID__referencedIDVID__PIID": "47QRAA19D000A",
    "contractID__referencedIDVID__modNumber": "PA0011",
```

**Comment by vdavez** [comment]
This is awesome! I just tried it out locally and it totally nailed my use case! Thank you so so much!
